name: order-processing-infra
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: 'Your!Passw0rd'
      ACCEPT_EULA: 'Y'
    volumes:
      - 'sql_data:/var/opt/mssql'
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672' # management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
    restart: unless-stopped
  webapis:
    build:
      context: .
      dockerfile: src/Presentation/WebAPIs/Dockerfile
    container_name: webapis
    image: webapis:latest
    ports:
      - "5032:8080"
    depends_on:
      - mssql
      - rabbitmq
  ordereventservice:
    build:
      context: .
      dockerfile: src/Presentation/OrderEventService/Dockerfile
    image: ordereventservice:latest
    scale: 2
    depends_on:
      - mssql
      - rabbitmq
  orderpages:
    build:
      context: .
      dockerfile: src/Presentation/OrderPages/Dockerfile
    container_name: orderpages
    image: orderpages:latest
    ports:
      - "5033:8081"
    depends_on:
      - mssql
      - rabbitmq
volumes:
  sql_data:
    driver: local
  rabbitmq_data:
    driver: local
